### ISSUE TITLE
GCC 7 wpebackend-rdk compile error

### ISSUE THREAD

**Issue by TomMettam** [WebPlatformForEmbedded/meta-wpe#236]
While following the instructions precisely at https://github.com/WebPlatformForEmbedded/meta-wpe/wiki/Raspberry-PI and running "bitbake wpe-westeros-image", the following compile error occurs:

`wpebackend-rdk/0.1-r0/git/src/westeros/WesterosViewbackendInput.cpp:147:13:` error: return-statement with no value, in function returning 'gboolean' {aka 'int'} [-fpermissive]
|              return;`

**Comment by outbackdingo** [comment]
seeing the same here, so i consider this a blocker, can we get it fxed?

WARNING: Your host glibc verson (2.28) is newer than that in uninative (2.27). Disabling uninative so that sstate is not corrupted.
Initialising tasks: 100% |######################################################################################################################################################################################################################################################################################| Time: 0:00:02
Sstate summary: Wanted 457 Found 0 Missed 457 Current 998 (0% match, 68% complete)
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: wpebackend-rdk-0.1-r0 do_compile: Function failed: do_compile (log file is located at /home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/temp/log.do_compile.12558)
ERROR: Logfile of failure stored in: /home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/temp/log.do_compile.12558
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: VERBOSE=1 cmake --build /home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/build --target all -- -j 8
| [1/2] /home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/recipe-sysroot-native/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++  -DBACKEND_WESTEROS=1 -DKEY_INPUT_HANDLING_VIRTUAL=1 -DWPEBackend_rdk_EXPORTS -I/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/recipe-sysroot/usr/include/WPEFramework/virtualinput -I/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/git/src/input -I/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/git/src/util -I/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/recipe-sysroot/usr/include/gio-unix-2.0 -I/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/recipe-sysroot/usr/include/glib-2.0 -I/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/recipe-sysroot/usr/lib/glib-2.0/include -I/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/recipe-sysroot/usr/include/wpe-0.2 -I/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/recipe-sysroot/usr/include -march=armv7ve -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0=/usr/src/debug/wpebackend-rdk/0.1-r0 -fdebug-prefix-map=/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/recipe-sysroot= -fdebug-prefix-map=/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -march=armv7ve -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/recipe-sysroot -std=c++1y -fno-exceptions -fno-strict-aliasing -fno-rtti -DNDEBUG -fPIC -MD -MT CMakeFiles/WPEBackend-rdk.dir/src/westeros/WesterosViewbackendInput.cpp.o -MF CMakeFiles/WPEBackend-rdk.dir/src/westeros/WesterosViewbackendInput.cpp.o.d -o CMakeFiles/WPEBackend-rdk.dir/src/westeros/WesterosViewbackendInput.cpp.o -c /home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/git/src/westeros/WesterosViewbackendInput.cpp
| FAILED: CMakeFiles/WPEBackend-rdk.dir/src/westeros/WesterosViewbackendInput.cpp.o
| /home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/recipe-sysroot-native/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++  -DBACKEND_WESTEROS=1 -DKEY_INPUT_HANDLING_VIRTUAL=1 -DWPEBackend_rdk_EXPORTS -I/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/recipe-sysroot/usr/include/WPEFramework/virtualinput -I/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/git/src/input -I/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/git/src/util -I/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/recipe-sysroot/usr/include/gio-unix-2.0 -I/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/recipe-sysroot/usr/include/glib-2.0 -I/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/recipe-sysroot/usr/lib/glib-2.0/include -I/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/recipe-sysroot/usr/include/wpe-0.2 -I/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/recipe-sysroot/usr/include -march=armv7ve -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0=/usr/src/debug/wpebackend-rdk/0.1-r0 -fdebug-prefix-map=/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/recipe-sysroot= -fdebug-prefix-map=/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -march=armv7ve -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/recipe-sysroot -std=c++1y -fno-exceptions -fno-strict-aliasing -fno-rtti -DNDEBUG -fPIC -MD -MT CMakeFiles/WPEBackend-rdk.dir/src/westeros/WesterosViewbackendInput.cpp.o -MF CMakeFiles/WPEBackend-rdk.dir/src/westeros/WesterosViewbackendInput.cpp.o.d -o CMakeFiles/WPEBackend-rdk.dir/src/westeros/WesterosViewbackendInput.cpp.o -c /home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/git/src/westeros/WesterosViewbackendInput.cpp
| /home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/git/src/westeros/WesterosViewbackendInput.cpp: In lambda function:
| /home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/git/src/westeros/WesterosViewbackendInput.cpp:147:13: error: return-statement with no value, in function returning 'gboolean' {aka 'int'} [-fpermissive]
|              return;
|              ^~~~~~
| ninja: build stopped: subcommand failed.
| WARNING: /home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/temp/run.do_compile.12558:1 exit 1 from 'eval ${DESTDIR:+DESTDIR=${DESTDIR} }VERBOSE=1 cmake --build '/home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/build' "$@" -- -j 8'
| ERROR: Function failed: do_compile (log file is located at /home/dingo/WPE/rpi-yocto/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpebackend-rdk/0.1-r0/temp/log.do_compile.12558)
ERROR: Task (/home/dingo/WPE/rpi-yocto/meta-wpe/recipes-wpe/wpebackend-rdk/wpebackend-rdk_0.1.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2661 tasks of which 2651 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/dingo/WPE/rpi-yocto/meta-wpe/recipes-wpe/wpebackend-rdk/wpebackend-rdk_0.1.bb:do_compile
Summary: There were 2 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

**Comment by kraj** [comment]
it is a valid error from compiler. Code needs to be fixed.

**Comment by wouterlucas** [comment]
Fixed in wpebackend https://github.com/WebPlatformForEmbedded/WPEBackend-rdk/commit/ad954707dca691f850560980e6786c0206e96891 and bumped with https://github.com/WebPlatformForEmbedded/meta-wpe/commit/eac415a0304c0407aad6aa02daa92aa81d2606db

Thanks for reporting!
