### ISSUE TITLE
Question: How does this layer relate to meta-webkit?

### ISSUE THREAD

**Issue by petrosagg** [WebPlatformForEmbedded/meta-wpe#276]
I've been using this layer to build WPE and I see that the default version shipped is 20170728 but also has a WIP for 2.22. 

At the same time I saw that WPE is shipped in Igalia's [meta-webkit](https://github.com/Igalia/meta-webkit) layer which seems to be updated less frequently (last change 2 months ago).

How are these two layers related? Is one of them having stable releases and one is dev? Do they have more fundamental differences? Are they maintained by different teams?

And more general, how does one choose which of those layers to use?

Thanks

**Comment by wouterlucas** [comment]
Hi @petrosagg sorry for not noticing the question up until now. FWIW:

This layer and its components are more focussed on WPEFramework/Thunder builds that include WPEWebKit as one of the dependencies. We only build the downstream WPEWebKit repo and are much more focussed on very specific devices (i.e. STBs, SmartTVs). We include WPEFramework (aka Thunder) which provides a starting point to manager a lot more services, such as manipulating WiFi, Remote Control, Network processes, Bluetooth, Compositor, etc. instead of just WPEWebKit alone. All of those services can be found here: https://github.com/WebPlatformForEmbedded/ThunderNanoServices/blob/master/README.md

Meta-webkit's primary focus is WPEWebkit. Which means building all versions of WPEWebKit, upstream and downstream for development and evaluation. As such they launch WPEWebKit through different launchers (e.g. cog) and using different backends (fdo vs rdk). 

In general if your only concern is WPEWebKit and you'd like to run that on an entire distro (e.g. with a Wayland desktop), you're most likely beter off using the meta-webkit layer. But if you are looking for an entire platform for an embedded device without any distro components, which includes WPEWebKit as one of its main runtimes, I'd suggest to start here.
